### ISSUE TITLE
Support for multiple namespaces!

### ISSUE THREAD

**Issue by sumitkumarm** [jonnylangefeld/kubectl-mc#14]
Thank you for creating this! Really like the ability to query multiple clusters in parallel.

It will be awesome if this can be extended to support multiple namespaces using an option like `-ns`.

```sh
kubectl mc -r prod -ns my-ns-1,my-ns-2,my-ns-3 -- get deployments
```

Not all `kubectl` commands accept multiple namespaces and depending on security setup, it may not always be possible to use the `-a` option.

For scenarios where a namespace has been specified in the command, the `-ns` switch may be ignored

**Comment by jonnylangefeld** [comment]
Sounds like a good idea and a useful feature! I'll see when I have time next, otherwise I'll gratefully accept PRs!

**Comment by sumitkumarm** [comment]
Made a first attempt at a PR: https://github.com/jonnylangefeld/kubectl-mc/pull/15

**Comment by jonnylangefeld** [comment]
Cool, thanks! Will take a look over the weekend!
