### ISSUE TITLE
heads up: codecov.io security incident - https://about.codecov.io/security-update/

### ISSUE THREAD

**Issue by robert-heinzmann-logmein** [jonnylangefeld/kubectl-mc#17]
Hi there.

This might be an unusual "issue" beeing reported.

There has been a security incident in codecov.io with the bash-uploader script (see [1] for details) which potentially exposed secrets to 3rd parties.

It seems you are using codecov, but I did not find any reference to the mentioned bash uploader script. I wanted to draw your attention to this incident in case you missed it.

It would be great if you could verify that no code has been altered and check the impact of this security incident on your repository.

Regards,
Robert

[1] https://about.codecov.io/security-update/

**Comment by jonnylangefeld** [comment]
Thanks for filing this issue. I am aware of the codecov incident. This repo is public that's why codecov doesn't need any secrets to run the coverage report on it (see [here](https://github.com/codecov/codecov-action/blame/master/README.md#L23)).
